create table if not exists public.healthcheck (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

-- opcional: una fila para que siempre haya algo
insert into public.healthcheck default values;